version: '3'
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: transmute-coffee.app
        container_name: transmute-coffee.app
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
